<div id="planes-summary" data-bind="scope: 'planes-summary'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#planes-summary": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "planes-summary": {
                        "component": "Yannerio_Calculadora/js/planes/summary",
                        "template" : "Yannerio_Calculadora/planes/summary"
                    }
                }
            }
        }
    }
    </script>
   
</div>