
<?php 
  // Instance of Object Manager
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
  
  if ($currentProduct = $block->getCurrentProduct()) {  
    $price = $priceHelper->currency($currentProduct->getFinalPrice(), true, false); 
    $planes = $currentProduct->getPlanes();
    
    $_planes = $this->getPlanes($planes);
  }
?>
<button type="button" class="action primary" data-toggle="modal" data-target="#exampleModal">Calcular cuotas</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Calculadora de planes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form id="calculadora" name="calculadora" method="POST">
        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey(); ?>" />
          <div class="form-group row cuota-plan">
            <div class="col-sm-10">
              <label for="" style="font-size: 30px;">Cuota:   <span id="cuota"></span></label>
            </div>
          </div>
          <div class="form-group row  cuota-plan">
            <div class="col-sm-10">
              <label for="" style="font-size: 30px;">Total del Plan:  <span id="total"></span></label>
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Plazo</label>
            <div class="col-sm-10">
            <select id="plazos" name="plazos" class="form-control" required="required">
              <option selected value="">Selecione un plazo</option>
              <?php foreach ($_planes as $key => $value) { ?>
              <option value="<?php echo $key ?>"><?php echo $value ?></option>
              <?php } ?>
            </select>
            </div>
          </div>
          <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Interes</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" id="interes" value="0.00%">
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Precio de contado</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" id="precio" value="<?php echo $price ?>">
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Cantidad</label>
            <div class="col-sm-10">
              <input type="text" readonly class="form-control-plaintext" id="cantidad" name="cantidad">
            </div>
          </div>
          
          <div class="row">
            <div class="col float-right">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
              <button type="submit" class="btn btn-primary calcular" name="calcular">Calcular</button>
              <input type="submit" id="addtocart2"  name="calculate" class="btn btn-primary cuota-plan" value="Add to cart">
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
<script>
requirejs(['jquery','bootstrap4'],function(){
    jQuery(document).ready(function() {

        jQuery("#cantidad").val(jQuery("#qty").val());
        jQuery('input[name=qty]').change(function() {jQuery("#cantidad").val(jQuery("#qty").val())});
        
        jQuery("#calculadora").submit(function(){
            var url = "<?php echo $block->getBaseUrl().'calculadora/planes/general/' ?>";
            
            if(jQuery("#plazos").val() != ""){
              jQuery.ajax({
                url: url,
                type: "POST",
                data: {id:jQuery("#plazos").val(), price:'<?php echo $currentProduct->getFinalPrice() ?>', qty: jQuery("#qty").val()},
                showLoader: true,
                cache: false,
                success: function(response){
                  jQuery("#cuota").html(response.cuota);
                  jQuery("#total").html(response.total_plan);
                  jQuery("#interes").val( response.interes + '%')
                  jQuery(".cuota-plan").show();
                    console.log(response);
                }
              });
            }else{
              jQuery("#plazos").focus()
            }
          return false;
        });
        jQuery("#addtocart2").click(function(){
          jQuery("#product_addtocart_form").submit();
          return false;
        });
    });
});
</script>
<style>
  .cuota-plan{
    display: none;
  }
</style>